Qa
cirKITers/mind-the-qapp pull request #45
Opened 2024-11-11 12:48 UTC by stroblme

This PR resolves #41 

**Depends on #44**

2024-11-11 12:48 UTC, pep8speaks commented
Hello @stroblme! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`app/pages/1-training.py`](https://github.com/cirKITers/mind-the-qapp/blob/400b1b9419431eae91ba028a0dc7dab5e076fbaf/app/pages/1-training.py):

> [Line 146:89](https://github.com/cirKITers/mind-the-qapp/blob/400b1b9419431eae91ba028a0dc7dab5e076fbaf/app/pages/1-training.py#L146): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 88 characters)
> [Line 204:89](https://github.com/cirKITers/mind-the-qapp/blob/400b1b9419431eae91ba028a0dc7dab5e076fbaf/app/pages/1-training.py#L204): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 88 characters)
> [Line 457:89](https://github.com/cirKITers/mind-the-qapp/blob/400b1b9419431eae91ba028a0dc7dab5e076fbaf/app/pages/1-training.py#L457): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 88 characters)

2024-11-11 12:50 UTC, stroblme commented
Just thought it would have been smarter to first address #38 , because flake now complains a lot.. well know what to do now..

2024-11-14 07:58 UTC, stroblme commented
checks failing because of #cirKITers/qml-essentials/pull/62 . Would suggest to merge as licensecheck issues are being resolved when upgrading qml essentials

2024-11-14 16:55 UTC, majafranz requested changes
Apart from the missing elements in the side bar, it looks good. Thanks for the great work!

2024-11-14 18:22 UTC, stroblme commented on app/app.py
> +from layouts.app_page_layout import sidebar, content
Hm, strange, could you try with a clean session, i.e. in a private tab?

2024-11-15 09:08 UTC, stroblme commented on app/app.py
> +from layouts.app_page_layout import sidebar, content
interesting.. in my case it's working fine.. if it's not working, then let's move the sidebar back into app.py

2024-11-15 12:47 UTC, majafranz approved these changes
Moved sidebar pages back to app

2024-11-15 12:48 UTC, merged